server:
  port: 9000
  tomcat:
    basedir: target/tomcat
    accesslog:
      enabled: true
      buffered: false
      directory: logs
      pattern: common

data:
  reload-interval: 3600000
  jhu:
    time-series:
      confirmed: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
      deaths: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
      recovered: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

